import turtle
t = turtle.Turtle()
t.pensize(5)
t.speed(10)
def move(x, y):
    t.penup()
    t.goto(x, y)
    t.pendown()
#Ashok Chakra
t.color("#054188")
for i in range(24):
    t.forward(80)
    t.backward(80)
    t.left(15)
move(0, -80)
t.circle( 80, 360)
#Green
t.begin_fill()
t.color("green")
t.forward(350)
t.backward(700)
t.right(90)
t.forward(200)
t.left(90)
t.forward(700)
t.left(90)
t.forward(200)
t.left(90)
t.end_fill()
#Orange
t.color("orange")
move(-350, 80)
t.begin_fill()
t.right(180)
t.forward(700)
t.left(90)
t.forward(200)
t.left(90)
t.forward(700)
t.left(90)
t.forward(200)
t.end_fill()
# writing text
text = turtle.Turtle()
text.hideturtle()
text.speed(2)
def write(message,pos,color):
    x,y = pos
    text.color(color)
    text.penup()
    text.goto(x,y)
    text.pendown()
    style = ('Courier',40,'italic')
    text.write(message,font=style)
write("'HAPPY",(100,10),'dark orange')
write('REPUBLIC  ',(80,-40),'blue')
write("  DAY  26/01/2024'",(120,-80),'dark green')
write('BY' ,(440,-200),'black')
write("NAVNATH ",(360,-240), 'BLACK')
turtle.done()